name: Keep Render Backend Alive

on:
  schedule:
    - cron: "*/1 * * * *"   # every 1 minute
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render backend
        run: |
          curl -m 10 -s -o /dev/null -w "Status: %{http_code}\n" \
          https://mentalan-backend.onrender.com/alive